apiVersion: batch/v1
kind: Job
metadata:
  name: ecommerce-test-job
  namespace: ecommerce-argocd
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test-job
          image: busybox:1.36
          command:
            - sh
            - -c
            - echo "E-commerce Kubernetes Job executed successfully"
  backoffLimit: 2

